#!/usr/bin/env python3
"""
Bybit public API connectivity test for GitHub Actions.

Purpose:
- Check whether GitHub-hosted runner can reach Bybit public V5 market API.
- Verify instruments, tickers, kline and open-interest endpoints.
- Print enough diagnostics to understand if failure is CloudFront / regional / network / JSON/API-level.

No API keys are required.
"""

from __future__ import annotations

import json
import os
import sys
import time
from dataclasses import dataclass
from typing import Any, Dict, Iterable, Optional

import requests

BASE_URL = os.getenv("BYBIT_BASE_URL", "https://api.bybit.com").rstrip("/")
TIMEOUT = float(os.getenv("BYBIT_TEST_TIMEOUT", "15"))
SYMBOLS = [s.strip().upper() for s in os.getenv("BYBIT_TEST_SYMBOLS", "BTCUSDT,WLDUSDT,UNIUSDT").split(",") if s.strip()]

SESSION = requests.Session()
SESSION.headers.update(
    {
        "User-Agent": "market-heat-scanner-bybit-connectivity-test/1.0",
        "Accept": "application/json,text/plain,*/*",
    }
)


@dataclass
class TestResult:
    name: str
    url: str
    ok_http: bool = False
    ok_json: bool = False
    ok_retcode: bool = False
    status_code: Optional[int] = None
    ret_code: Optional[int] = None
    error: Optional[str] = None
    cloudfront_block: bool = False
    elapsed_ms: Optional[int] = None

    @property
    def passed(self) -> bool:
        return self.ok_http and self.ok_json and self.ok_retcode


def short_text(text: str, limit: int = 500) -> str:
    text = (text or "").replace("\n", " ").replace("\r", " ").strip()
    if len(text) <= limit:
        return text
    return text[:limit] + "..."


def is_cloudfront_block(text: str) -> bool:
    lower = (text or "").lower()
    markers = [
        "the amazon cloudfront distribution is configured to block access",
        "request could not be satisfied",
        "generated by cloudfront",
        "cloudfront",
    ]
    return any(m in lower for m in markers)


def call_endpoint(name: str, path: str, params: Optional[Dict[str, Any]] = None) -> TestResult:
    url = f"{BASE_URL}{path}"
    result = TestResult(name=name, url=url)
    start = time.monotonic()

    print("\n" + "=" * 100)
    print(f"TEST: {name}")
    print(f"GET:  {url}")
    if params:
        print(f"PARAMS: {json.dumps(params, ensure_ascii=False, sort_keys=True)}")

    try:
        response = SESSION.get(url, params=params, timeout=TIMEOUT)
        result.elapsed_ms = int((time.monotonic() - start) * 1000)
        result.status_code = response.status_code
        result.ok_http = 200 <= response.status_code < 300

        content_type = response.headers.get("content-type", "")
        body_preview = short_text(response.text)
        result.cloudfront_block = is_cloudfront_block(response.text)

        print(f"HTTP: {response.status_code} | elapsed={result.elapsed_ms}ms | content-type={content_type}")
        print(f"BODY_PREVIEW: {body_preview}")

        try:
            data = response.json()
            result.ok_json = True
            result.ret_code = data.get("retCode")
            result.ok_retcode = result.ret_code == 0
            print(f"JSON: ok | retCode={result.ret_code} | retMsg={data.get('retMsg')}")

            # Print a compact result shape for useful endpoints.
            payload = data.get("result")
            if isinstance(payload, dict):
                if isinstance(payload.get("list"), list):
                    print(f"RESULT_LIST_LEN: {len(payload.get('list'))}")
                    if payload.get("list"):
                        print(f"FIRST_ITEM: {short_text(json.dumps(payload.get('list')[0], ensure_ascii=False), 700)}")
                else:
                    print(f"RESULT_KEYS: {sorted(payload.keys())}")
        except Exception as exc:  # noqa: BLE001
            result.ok_json = False
            result.error = f"JSON parse error: {exc}"
            print(f"JSON: failed | {exc}")

    except requests.exceptions.RequestException as exc:
        result.elapsed_ms = int((time.monotonic() - start) * 1000)
        result.error = repr(exc)
        print(f"REQUEST_ERROR: {result.error} | elapsed={result.elapsed_ms}ms")

    print(
        "PASS:" if result.passed else "FAIL:",
        f"http={result.ok_http}",
        f"json={result.ok_json}",
        f"retCode0={result.ok_retcode}",
        f"cloudfront_block={result.cloudfront_block}",
    )
    return result


def main() -> int:
    print("Bybit public API connectivity test")
    print(f"BASE_URL={BASE_URL}")
    print(f"TIMEOUT={TIMEOUT}")
    print(f"SYMBOLS={SYMBOLS}")
    print(f"PYTHON={sys.version}")

    tests: list[tuple[str, str, Optional[Dict[str, Any]]]] = [
        ("server_time", "/v5/market/time", None),
        ("linear_instruments_sample", "/v5/market/instruments-info", {"category": "linear", "limit": "5"}),
        ("btc_ticker", "/v5/market/tickers", {"category": "linear", "symbol": "BTCUSDT"}),
        ("btc_kline_1h", "/v5/market/kline", {"category": "linear", "symbol": "BTCUSDT", "interval": "60", "limit": "5"}),
        ("btc_open_interest_1h", "/v5/market/open-interest", {"category": "linear", "symbol": "BTCUSDT", "intervalTime": "1h", "limit": "5"}),
        ("btc_open_interest_4h", "/v5/market/open-interest", {"category": "linear", "symbol": "BTCUSDT", "intervalTime": "4h", "limit": "5"}),
    ]

    for symbol in SYMBOLS:
        if symbol == "BTCUSDT":
            continue
        tests.extend(
            [
                (f"{symbol}_instrument", "/v5/market/instruments-info", {"category": "linear", "symbol": symbol}),
                (f"{symbol}_ticker", "/v5/market/tickers", {"category": "linear", "symbol": symbol}),
                (f"{symbol}_kline_1h", "/v5/market/kline", {"category": "linear", "symbol": symbol, "interval": "60", "limit": "5"}),
                (f"{symbol}_open_interest_1h", "/v5/market/open-interest", {"category": "linear", "symbol": symbol, "intervalTime": "1h", "limit": "5"}),
                (f"{symbol}_open_interest_4h", "/v5/market/open-interest", {"category": "linear", "symbol": symbol, "intervalTime": "4h", "limit": "5"}),
            ]
        )

    results = [call_endpoint(name, path, params) for name, path, params in tests]

    print("\n" + "=" * 100)
    print("SUMMARY")
    passed = [r for r in results if r.passed]
    cloudfront = [r for r in results if r.cloudfront_block or r.status_code == 403]
    oi_passed = [r for r in passed if "open_interest" in r.name]

    print(f"TOTAL_TESTS={len(results)}")
    print(f"PASSED={len(passed)}")
    print(f"HTTP_403_OR_CLOUDFRONT={len(cloudfront)}")
    print(f"OI_TESTS_PASSED={len(oi_passed)}")

    if cloudfront and not passed:
        print("FINAL_STATUS=BLOCKED_BY_CDN_OR_REGION")
        return 2
    if not passed:
        print("FINAL_STATUS=NO_SUCCESSFUL_BYBIT_ENDPOINTS")
        return 1
    if not oi_passed:
        print("FINAL_STATUS=MARKET_API_REACHABLE_BUT_OI_FAILED")
        return 1

    print("FINAL_STATUS=BYBIT_PUBLIC_MARKET_AND_OI_API_REACHABLE")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
